apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: sachetx21/three-tier-frontend:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://k8s-threetie-mainlb-73c240e86c-980289364.eu-north-1.elb.amazonaws.com/api/tasks" # "http://zone.dial12.com/api/tasks" 
#            value: "http://192.168.49.2:30035/api/tasks"
#refrence video time @ 1 he 59 min
        ports:
        - containerPort: 3000