apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: mongo-sec
type: Opaque
data:  
  password: cGFzc3dvcmQxMjM=   #password123
  username: YWRtaW4= #admin

# echo "admin" | base64
# echo 'YWRtaW4=' | base64 --decode

#echo 'cGFzc3dvcmQxMjM=' | base64 --decode